### ISSUE TITLE
Contrast Ratio

### ISSUE THREAD

**Issue by justincavery** [corysimmons/corysimmons.com#2]
Hi Cory,

I ended up on your blog via a GH Issue on Susy Grids... Love the content but the home page is a little hard to read with text contrast against the background.

Most people are probably fine, but something worth looking at if you fancy it.

After a quick test on http://webaim.org/resources/contrastchecker/?fcolor=b4c0cc it looks like you'll get AA and AAA pass if you bumped it up to #445263

**Comment by corysimmons** [comment]
I'll meet you more than halfway: https://github.com/corysimmons/corysimmons.com/blob/master/static/src/css/style.styl#L11

Updated. Refresh and let me know if it works for you. 👍

**Comment by justincavery** [comment]
Looks great (looked great anyway, but even easier to read now)

**Comment by corysimmons** [comment]
I'm glad it reads better for you. =)
